### ISSUE TITLE
Деплой на хост

### ISSUE THREAD

**Issue by pva15t118** [dmarichuk/bolice#16]
Договорились в лс, что будем паковать в бинарь, затем отправлять на хост

**Comment by pva15t118** [comment]
Добавлен воркфлоу на сборку через pyinstaller и загрузку артефакта в виде исполняемого бинаря

**Comment by pva15t118** [comment]
UPD
Кажется, проще и прозрачнее паковать в докер. Таким образом, деплой примет вид:
1. Проверить код
2. Сконфигурировать окружение
3. Закатать в докер
4. Выдать образ
5. Накатить образ на сервере, предварительно остановив предыдущий

**Comment by dmarichuk** [comment]
Сделано
