### ISSUE TITLE
Создать админский интерфейс

### ISSUE THREAD

**Issue by dmarichuk** [dmarichuk/bolice#35]
Вопрос, что туда включать. Предложения?

**Comment by pva15t118** [comment]
Хм ну это я бы делал, когда уже функционал разрастется. Сейчас и админист-то особо нечего, только если критический процент совпадения хэша

**Comment by dmarichuk** [comment]
Согласен, оставим на потом

**Comment by pva15t118** [comment]
Мидл на вопрос "можешь ли ты это сделать" отвечает - могу. Синьор отвечает - "могу, но не буду")
