### ISSUE TITLE
Команда для голосования на мут участника

### ISSUE THREAD

**Issue by dmarichuk** [dmarichuk/bolice#36]
Команда '!отдохни @username' вызывает голосование на мут участника

**Comment by pva15t118** [comment]
Тут надо бы не давать пользаку голосовать. Хз, Как это сделать, правда. А то бывает сам себя от мьюта спасает

**Comment by pva15t118** [comment]
Возможно, встроенную голосовалку заменить на кастомные кнопки. Это позволит отсеивать лишних голосующих, но сделает голосование анонимным (что может и хорошо)

**Comment by dmarichuk** [comment]
Ну после окончания голосования, можно глянуть кто голосовал и голос обвиняемого вычесть. Это кстати можно прям в отдельной функции сделать, которая и при баяне возникает. Плюс, мб к команде добавить аргумент, чтобы в обвинение вставлял что то. Напрммер, '!обвинить @username скинул баян'
